-- ============================================================
-- Feria — esquema PostgreSQL
-- Modelo: vendedor único (la plataforma). Los feriantes aceptan
-- sub-pedidos por broadcast y se les paga en efectivo en la tarde.
--
-- Todos los instantes son timestamptz: la feria abre a una hora
-- local y el servidor puede estar en cualquier parte.
-- ============================================================

-- ---------- Catálogo (precio fijado por la plataforma) ----------

CREATE TABLE IF NOT EXISTS rubros (
  id            text PRIMARY KEY,          -- 'verduras', 'frutas', 'pescado'
  nombre        text NOT NULL
);

CREATE TABLE IF NOT EXISTS productos (
  id            text PRIMARY KEY,
  rubro_id      text NOT NULL REFERENCES rubros(id),
  nombre        text NOT NULL,             -- 'Tomate'
  formato       text NOT NULL,             -- 'Malla 1 kg aprox.'
  precio_venta  integer NOT NULL,          -- CLP, lo que paga el cliente
  precio_costo  integer NOT NULL,          -- CLP, lo que le pagas al feriante
  activo        boolean NOT NULL DEFAULT true,
  /** Foto del producto. La app muestra un marcador si falta. */
  imagen_url    text,
  shopify_variant_id text                  -- enlace al catálogo de Shopify
);

CREATE INDEX IF NOT EXISTS idx_productos_rubro ON productos(rubro_id) WHERE activo;
CREATE UNIQUE INDEX IF NOT EXISTS idx_productos_variante
  ON productos(shopify_variant_id) WHERE shopify_variant_id IS NOT NULL;

-- ---------- Actores ----------

CREATE TABLE IF NOT EXISTS feriantes (
  id            text PRIMARY KEY,
  nombre        text NOT NULL,
  puesto        text NOT NULL,             -- 'Puesto 42, pasillo B'
  feria_id      text NOT NULL,
  telefono      text NOT NULL,
  conectado     boolean NOT NULL DEFAULT false,
  push_token    text,
  -- ubicación del puesto dentro de la feria (para la ruta de retiro)
  lat           double precision,
  lng           double precision,
  -- reputación: se recalcula desde ofertas/sub_pedidos
  aceptaciones  integer NOT NULL DEFAULT 0,
  rechazos      integer NOT NULL DEFAULT 0,
  timeouts      integer NOT NULL DEFAULT 0,
  incumplidos   integer NOT NULL DEFAULT 0, -- aceptó y después no tenía
  creado_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_feriantes_disponibles
  ON feriantes(feria_id) WHERE conectado;

CREATE TABLE IF NOT EXISTS feriante_rubros (
  feriante_id   text NOT NULL REFERENCES feriantes(id) ON DELETE CASCADE,
  rubro_id      text NOT NULL REFERENCES rubros(id),
  PRIMARY KEY (feriante_id, rubro_id)
);

CREATE TABLE IF NOT EXISTS repartidores (
  id            text PRIMARY KEY,
  nombre        text NOT NULL,
  vehiculo      text NOT NULL,             -- 'moto', 'auto', 'bici'
  telefono      text NOT NULL,
  conectado     boolean NOT NULL DEFAULT false,
  push_token    text,
  lat           double precision,
  lng           double precision,
  ubicacion_at  timestamptz
);

-- ---------- Pedidos ----------

CREATE TABLE IF NOT EXISTS pedidos (
  id                text PRIMARY KEY,
  shopify_order_id  text UNIQUE,           -- NULL si el pedido es interno/manual
  -- Correlativo legible (#1042). Secuencia y no MAX()+1: con dos
  -- pedidos entrando a la vez, MAX()+1 entrega el mismo número dos
  -- veces.
  numero            integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) UNIQUE,
  feria_id          text NOT NULL,
  cliente_nombre    text NOT NULL,
  cliente_telefono  text NOT NULL,
  -- Hace falta para devolverle la plata: la pasarela manda el
  -- reembolso a un correo, no a un teléfono.
  cliente_email     text,
  direccion         text NOT NULL,
  lat               double precision NOT NULL,
  lng               double precision NOT NULL,
  notas             text,
  -- Se guardan separados porque son cosas distintas: la mercadería
  -- se le paga a los feriantes y el despacho al repartidor.
  total_productos   integer NOT NULL,
  costo_despacho    integer NOT NULL DEFAULT 0,
  total_venta       integer NOT NULL,      -- productos + despacho
  estado            text NOT NULL,         -- ver dominio/estados.ts
  creado_at         timestamptz NOT NULL DEFAULT now(),
  entregado_at      timestamptz
);

CREATE INDEX IF NOT EXISTS idx_pedidos_estado ON pedidos(estado);
CREATE INDEX IF NOT EXISTS idx_pedidos_dia ON pedidos(creado_at);

-- Un pedido se parte en sub-pedidos por rubro. Cada sub-pedido
-- se ofrece por separado y lo cumple UN feriante (o el operador).
CREATE TABLE IF NOT EXISTS sub_pedidos (
  id              text PRIMARY KEY,
  pedido_id       text NOT NULL REFERENCES pedidos(id) ON DELETE CASCADE,
  rubro_id        text NOT NULL REFERENCES rubros(id),
  monto_feriante  integer NOT NULL,        -- CLP que se le paga al feriante
  estado          text NOT NULL,
  feriante_id     text REFERENCES feriantes(id),
  ronda           integer NOT NULL DEFAULT 0,
  -- Queda en true apenas el sub-pedido cae en autogestión, y no se
  -- borra cuando avanza a LISTO. Sin esta marca, la métrica de
  -- "cuánto terminé haciendo yo" se pierde al final del día.
  autogestionado  boolean NOT NULL DEFAULT false,
  -- El feriante aceptó y apartó la mercadería, y después el pedido
  -- se canceló. Se le paga igual: la mercadería ya está separada y
  -- la culpa no es suya. Es lo que protege la relación con el
  -- puesto, que es el recurso más escaso del negocio.
  compensado      boolean NOT NULL DEFAULT false,
  aceptado_at     timestamptz,
  listo_at        timestamptz,
  retirado_at     timestamptz,
  creado_at       timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sub_pedidos_pedido ON sub_pedidos(pedido_id);
CREATE INDEX IF NOT EXISTS idx_sub_pedidos_estado ON sub_pedidos(estado);
CREATE INDEX IF NOT EXISTS idx_sub_pedidos_liquidacion
  ON sub_pedidos(feriante_id, retirado_at) WHERE estado = 'RETIRADO';
CREATE INDEX IF NOT EXISTS idx_sub_pedidos_compensados
  ON sub_pedidos(feriante_id) WHERE compensado;

CREATE TABLE IF NOT EXISTS items (
  id              text PRIMARY KEY,
  sub_pedido_id   text NOT NULL REFERENCES sub_pedidos(id) ON DELETE CASCADE,
  producto_id     text NOT NULL REFERENCES productos(id),
  nombre          text NOT NULL,           -- snapshot: el catálogo cambia
  formato         text NOT NULL,
  cantidad        integer NOT NULL CHECK (cantidad > 0),
  precio_venta    integer NOT NULL,        -- snapshot unitario
  precio_costo    integer NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_items_sub ON items(sub_pedido_id);

-- ---------- Motor de despacho ----------

-- Una fila por (sub_pedido, feriante) al que se le ofreció.
-- Es la tabla de métricas más importante del sistema.
CREATE TABLE IF NOT EXISTS ofertas (
  id              text PRIMARY KEY,
  sub_pedido_id   text NOT NULL REFERENCES sub_pedidos(id) ON DELETE CASCADE,
  feriante_id     text NOT NULL REFERENCES feriantes(id),
  ronda           integer NOT NULL,
  enviada_at      timestamptz NOT NULL DEFAULT now(),
  expira_at       timestamptz NOT NULL,
  -- 'ACEPTA' | 'RECHAZA' | 'TIMEOUT' | 'CERRADA' | NULL (todavía abierta)
  respuesta       text,
  respondida_at   timestamptz,
  UNIQUE (sub_pedido_id, feriante_id, ronda)
);

CREATE INDEX IF NOT EXISTS idx_ofertas_sub ON ofertas(sub_pedido_id);
CREATE INDEX IF NOT EXISTS idx_ofertas_abiertas
  ON ofertas(feriante_id, expira_at) WHERE respuesta IS NULL;

-- ---------- Reparto ----------

CREATE TABLE IF NOT EXISTS viajes (
  id              text PRIMARY KEY,
  pedido_id       text NOT NULL REFERENCES pedidos(id) ON DELETE CASCADE,
  repartidor_id   text REFERENCES repartidores(id),
  estado          text NOT NULL,
  tarifa          integer NOT NULL,        -- CLP que gana el repartidor
  asignado_at     timestamptz,
  iniciado_at     timestamptz,
  entregado_at    timestamptz,
  creado_at       timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_viajes_estado ON viajes(estado);
-- Un pedido no puede tener dos viajes vivos a la vez.
CREATE UNIQUE INDEX IF NOT EXISTS idx_viajes_vivo
  ON viajes(pedido_id) WHERE estado <> 'CANCELADO';

-- Paradas del viaje: N puestos de retiro + 1 entrega al cliente.
CREATE TABLE IF NOT EXISTS paradas (
  id              text PRIMARY KEY,
  viaje_id        text NOT NULL REFERENCES viajes(id) ON DELETE CASCADE,
  orden           integer NOT NULL,
  tipo            text NOT NULL CHECK (tipo IN ('RETIRO', 'ENTREGA')),
  sub_pedido_id   text REFERENCES sub_pedidos(id) ON DELETE CASCADE,
  etiqueta        text NOT NULL,           -- 'Puesto 42 — Don José'
  lat             double precision,
  lng             double precision,
  completada_at   timestamptz,
  UNIQUE (viaje_id, orden)
);

CREATE INDEX IF NOT EXISTS idx_paradas_viaje ON paradas(viaje_id, orden);

-- Rastro GPS del repartidor durante el viaje (para el mapa del cliente).
CREATE TABLE IF NOT EXISTS ubicaciones (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  repartidor_id   text NOT NULL REFERENCES repartidores(id),
  viaje_id        text REFERENCES viajes(id) ON DELETE CASCADE,
  lat             double precision NOT NULL,
  lng             double precision NOT NULL,
  at              timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ubicaciones_viaje ON ubicaciones(viaje_id, at);

-- ---------- Liquidaciones (pago en efectivo en la tarde) ----------

CREATE TABLE IF NOT EXISTS liquidaciones (
  id                     text PRIMARY KEY,
  feriante_id            text NOT NULL REFERENCES feriantes(id),
  fecha                  date NOT NULL,
  monto_total            integer NOT NULL,
  cantidad_sub_pedidos   integer NOT NULL,
  pagado_at              timestamptz,
  confirmado_at          timestamptz,      -- el feriante marca "recibí" en su app
  UNIQUE (feriante_id, fecha)
);

-- ---------- Auditoría ----------

-- Todo cambio de estado queda registrado. Sin esto no se puede
-- depurar un despacho ni resolver una disputa de pago.
CREATE TABLE IF NOT EXISTS eventos (
  id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  entidad      text NOT NULL,              -- 'pedido' | 'sub_pedido' | 'viaje'
  entidad_id   text NOT NULL,
  tipo         text NOT NULL,
  detalle      jsonb,
  at           timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_eventos_entidad ON eventos(entidad, entidad_id, at);

-- ============================================================
-- Autenticación por SMS
--
-- El feriante pone su número, recibe un código de 6 dígitos y
-- queda con una sesión larga. Nada de contraseñas: es el único
-- método que va a usar sin ayuda.
-- ============================================================

-- El teléfono es la identidad, así que no puede repetirse: si dos
-- feriantes comparten número, no hay forma de saber quién entró.
CREATE UNIQUE INDEX IF NOT EXISTS idx_feriantes_telefono ON feriantes(telefono);
CREATE UNIQUE INDEX IF NOT EXISTS idx_repartidores_telefono ON repartidores(telefono);

-- Operadores: vos y quien más maneje la caja. Se cargan a mano.
CREATE TABLE IF NOT EXISTS operadores (
  id            text PRIMARY KEY,
  nombre        text NOT NULL,
  telefono      text NOT NULL UNIQUE,
  push_token    text,
  creado_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS codigos_acceso (
  id            text PRIMARY KEY,
  telefono      text NOT NULL,
  -- HMAC, no el código en limpio: quien lea la base no puede
  -- iniciar sesión como otro.
  codigo_hash   text NOT NULL,
  intentos      integer NOT NULL DEFAULT 0,
  creado_at     timestamptz NOT NULL DEFAULT now(),
  expira_at     timestamptz NOT NULL,
  usado_at      timestamptz
);

CREATE INDEX IF NOT EXISTS idx_codigos_telefono ON codigos_acceso(telefono, creado_at);
CREATE INDEX IF NOT EXISTS idx_codigos_vivos
  ON codigos_acceso(telefono) WHERE usado_at IS NULL;

CREATE TABLE IF NOT EXISTS sesiones (
  id            text PRIMARY KEY,
  -- Igual que el código: se guarda el hash, nunca el token.
  token_hash    text NOT NULL UNIQUE,
  rol           text NOT NULL CHECK (rol IN ('feriante', 'repartidor', 'operador')),
  actor_id      text NOT NULL,
  telefono      text NOT NULL,
  dispositivo   text,
  creada_at     timestamptz NOT NULL DEFAULT now(),
  expira_at     timestamptz NOT NULL,
  ultima_at     timestamptz,
  revocada_at   timestamptz
);

CREATE INDEX IF NOT EXISTS idx_sesiones_actor ON sesiones(actor_id)
  WHERE revocada_at IS NULL;


-- ============================================================
-- Pagos
--
-- Un pedido no se despacha hasta que la pasarela confirma. La
-- confirmación nunca se cree por lo que dice el callback: se le
-- vuelve a preguntar a la pasarela.
-- ============================================================

CREATE TABLE IF NOT EXISTS pagos (
  id                  text PRIMARY KEY,
  pedido_id           text NOT NULL REFERENCES pedidos(id) ON DELETE CASCADE,
  proveedor           text NOT NULL,          -- 'flow'
  -- Nuestro identificador, el que viaja a la pasarela. Único para
  -- que un reintento no genere dos cobros.
  orden_comercio      text NOT NULL UNIQUE,
  -- El identificador que devuelve la pasarela.
  referencia_externa  text,
  monto               integer NOT NULL,
  medio               text,                   -- 'tarjeta' | 'transferencia' | …
  estado              text NOT NULL,          -- INICIADO | PAGADO | RECHAZADO | ANULADO
  url_pago            text,
  monto_reembolsado   integer NOT NULL DEFAULT 0,
  reembolsado_at      timestamptz,
  creado_at           timestamptz NOT NULL DEFAULT now(),
  confirmado_at       timestamptz
);

CREATE INDEX IF NOT EXISTS idx_pagos_pedido ON pagos(pedido_id);
-- Un pedido no puede tener dos pagos confirmados.
CREATE UNIQUE INDEX IF NOT EXISTS idx_pagos_confirmado
  ON pagos(pedido_id) WHERE estado = 'PAGADO';

CREATE INDEX IF NOT EXISTS idx_pedidos_sin_pagar
  ON pedidos(creado_at) WHERE estado = 'PENDIENTE_PAGO';
